### ISSUE TITLE
error during packaging service

### ISSUE THREAD

**Issue by attinderseesdragons** [dougmoscrop/serverless-plugin-include-dependencies#12]
Serverless: Packaging service...
/usr/local/lib/node_modules/serverless/node_modules/minimatch/minimatch.js:918
  return s.replace(/\\(.)/g, '$1')
           ^

RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at globUnescape (/usr/local/lib/node_modules/serverless/node_modules/minimatch/minimatch.js:918:12)
    at Minimatch.parse (/usr/local/lib/node_modules/serverless/node_modules/minimatch/minimatch.js:617:12)
    at Array.map (native)
    at Minimatch.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/minimatch/minimatch.js:182:14)
    at Array.map (native)
    at Minimatch.make (/usr/local/lib/node_modules/serverless/node_modules/minimatch/minimatch.js:181:13)
    at new Minimatch (/usr/local/lib/node_modules/serverless/node_modules/minimatch/minimatch.js:136:8)
    at setopts (/usr/local/lib/node_modules/serverless/node_modules/glob/common.js:118:20)
    at new GlobSync (/usr/local/lib/node_modules/serverless/node_modules/glob/sync.js:40:3)
    at new Glob (/usr/local/lib/node_modules/serverless/node_modules/glob/glob.js:129:12)
    at GlobAll.globNext (/usr/local/lib/node_modules/serverless/node_modules/glob-all/glob-all.js:97:9)
    at GlobAll.globbedOne (/usr/local/lib/node_modules/serverless/node_modules/glob-all/glob-all.js:147:8)
    at GlobAll.globNext (/usr/local/lib/node_modules/serverless/node_modules/glob-all/glob-all.js:99:10)

**Comment by dougmoscrop** [comment]
This is covered in the readme :)

**Comment by attinderseesdragons** [comment]
Thanks

I see fix is merged too. What is eta on build into npm?

**Comment by dougmoscrop** [comment]
I can't say since it's in serverless itself. You can use it directly by
referencing the Sha in your package.json!

**Comment by smiller171** [comment]
Serverless version 1.9.0 seems to include the fix

**Comment by attinderseesdragons** [comment]
Thanks for the update
