### ISSUE TITLE
[serverless-plugin-include-dependencies]: Could not find aws-sdk

### ISSUE THREAD

**Issue by nkhine** [dougmoscrop/serverless-plugin-include-dependencies#13]
I don't include `aws-sdk` in my dependencies as this is already part of AWS http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

 ```
  Error --------------------------------------------------
 
     [serverless-plugin-include-dependencies]: Could not
     find aws-sdk
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: [serverless-plugin-include-dependencies]: Could not find aws-sdk
    at precinct.paperwork.forEach.name (/home/khinester/Projects/Trint/trint-serverless/ingest/node_modules/serverless-plugin-include-dependencies/get-dependency-list.js:47:17)
    at Array.forEach (native)
    at module.exports (/home/khinester/Projects/Trint/trint-serverless/ingest/node_modules/serverless-plugin-include-dependencies/get-dependency-list.js:28:42)
    at IncludeDependencies.getDependencyList (/home/khinester/Projects/Trint/trint-serverless/ingest/node_modules/serverless-plugin-include-dependencies/include-dependencies.js:108:12)
    at IncludeDependencies.getDependencies (/home/khinester/Projects/Trint/trint-serverless/ingest/node_modules/serverless-plugin-include-dependencies/include-dependencies.js:92:31)
    at IncludeDependencies.processNodeFunction (/home/khinester/Projects/Trint/trint-serverless/ingest/node_modules/serverless-plugin-include-dependencies/include-dependencies.js:70:33)
    at IncludeDependencies.processFunction (/home/khinester/Projects/Trint/trint-serverless/ingest/node_modules/serverless-plugin-include-dependencies/include-dependencies.js:54:12)
    at Object.keys.forEach.functionName (/home/khinester/Projects/Trint/trint-serverless/ingest/node_modules/serverless-plugin-include-dependencies/include-dependencies.js:37:14)
    at Array.forEach (native)
    at IncludeDependencies.createDeploymentArtifacts (/home/khinester/Projects/Trint/trint-serverless/ingest/node_modules/serverless-plugin-include-dependencies/include-dependencies.js:36:38)
    at BbPromise.reduce (/home/khinester/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/lib/classes/PluginManager.js:210:55)
From previous event:
    at PluginManager.invoke (/home/khinester/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/lib/classes/PluginManager.js:210:22)
    at PluginManager.run (/home/khinester/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/lib/classes/PluginManager.js:225:17)
    at Serverless.run (/home/khinester/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/lib/Serverless.js:97:31)
    at serverless.init.then (/home/khinester/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/bin/serverless:23:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       7.5.0
     Serverless Version: 1.11.0
```

**Comment by dougmoscrop** [comment]
Ah, sorry! Fixed in 2.0.3
