### ISSUE TITLE
"Cannot find modules" when compiling a TypeScript project

### ISSUE THREAD

**Issue by mushketyk** [dougmoscrop/serverless-plugin-include-dependencies#30]
When I try to deploy a serverless project with the `serverless-plugin-include-dependencies` plugin I get the following error:

```
Cannot find module '.../src/function'
```

With the following stacktrace:

```
Error: Cannot find module '.../src/function'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
    at IncludeDependencies.getHandlerFilename (.../node_modules/serverless-plugin-include-dependencies/include-dependencies.js:134:20)
```

I think the bug is that it is looking for a file `src/function` (that does not exist), while the file it should be looking for is `src/function.ts` that exists.

Here is my configuration:

```yml
plugins:
  - serverless-webpack
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-plugin-canary-deployments
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-plugin-include-dependencies

package:
  individually: true
```

Here is the version of the plugin that I use:

```json
"serverless-plugin-include-dependencies": "^3.2.1",
```

**Comment by dsmileym4** [comment]
We are experiencing this same issue.

**Comment by dougmoscrop** [comment]
I don't use TypeScript unfortunately! I'm open to PRs of course.

Don't you have to compile your .ts files in to .js files? Are those not referenced by serverless.yml or does it support TS directly?

**Comment by yzpaul** [comment]
> I don't use TypeScript unfortunately! I'm open to PRs of course.
> 
> Don't you have to compile your .ts files in to .js files? Are those not referenced by serverless.yml or does it support TS directly?

Serverless compiles TS into JS in <PROJ_ROOT>/.build

**Comment by HarshUpparwal** [comment]
any workaround this plugin?

Inspite of having file at said path, error msg pops up saying `Cannot find module`

**Comment by env-poehler** [comment]
I am also having this issue.  Has anyone figured out a work around?

**Comment by denis-ryzhkov** [comment]
@env-poehler, do you have both `serverless-plugin-include-dependencies` and `serverless-plugin-typescript` in `serverless.yml` and both are working? I had to delete `serverless-plugin-include-dependencies` to make it work.

**Comment by nick-verida** [comment]
I can confirm removing `serverless-plugin-include-dependencies` helped with this.

**Comment by jeison-od** [comment]
@denis-ryzhkov  I can confirm it too!

**Comment by brayoh** [comment]
Experiencing a similar issue, any updates on this?
